version: 0.2

env:
  variables:
    NODE_OPTIONS: "--max-old-space-size=4096"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Lerna..."
      - npm install -g lerna
      - echo "Installing Yarn..."
      - npm install -g yarn
      - echo "Installing dependencies..."
      - yarn config set maxsockets 15
      - yarn config set fetch-retries 5
      - yarn config set fetch-retry-mintimeout 20000
      - yarn config set fetch-retry-maxtimeout 120000
      - yarn cache clean
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - yarn install
  build:
    commands:
      - echo "Compiling TypeScript to JavaScript..."
      - npx swc src -d dist
      - echo "Pruning development dependencies..."
      - yarn run prune
      - echo "Packaging the SAM application..."
      - sam package --s3-bucket auto-garage-deployment --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
    - dist/**
