version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm config set maxsockets 5  # Limit concurrent connections
      - npm config set fetch-retries 5  # Increase retry attempts
      - npm config set fetch-retry-mintimeout 20000  # Increase minimum retry timeout
      - npm config set fetch-retry-maxtimeout 120000  # Increase maximum retry timeout
      - npm install -g npm@latest  # Update npm to the latest version
      - npm cache clean --force  # Clear npm cache
      - npm ci --no-audit --no-fund --prefer-offline  # Install dependencies with reduced network operations
      - npm install -g typescript modclean
  build:
    commands:
      - echo Compiling TypeScript to JavaScript...
      - npx tsc --outDir dist
      - echo Cleaning unnecessary files from node_modules...
      - modclean --run
      - echo Pruning development dependencies...
      - npm prune --production
      - cp -R node_modules dist/
      - echo Packaging the SAM application...
      - sam package --s3-bucket auto-garage-deployment --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
    - dist/**
