version: 0.2

env:
  variables:
    NODE_OPTIONS: "--max-old-space-size=4096"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Lerna..."
      - npm install -g lerna
      - echo "Installing dependencies..."
      - npm config set maxsockets 15
      - npm config set fetch-retries 5
      - npm config set fetch-retry-mintimeout 20000
      - npm config set fetch-retry-maxtimeout 120000
      - npm cache clean --force
  pre_build:
    commands:
      - echo "Installing production dependencies..."
      - lerna bootstrap --since-version-mode=fixed --ignore-scripts --no-ci --no-sort --no-symlink --only-updated --prefer-offline
  build:
    commands:
      - echo "Compiling TypeScript to JavaScript..."
      - lerna run --parallel build
      - echo "Pruning development dependencies..."
      - lerna clean -y
      - echo "Packaging the SAM application..."
      - sam package --s3-bucket auto-garage-deployment --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
    - packages/*/dist/**
