version: 0.2

env:
  variables:
    NODE_OPTIONS: "--max-old-space-size=4096"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Yarn..."
      - npm install -g yarn
      - npm install -g typescript modclean
      - yarn cache clean
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - yarn install
  build:
    commands:
      - echo Compiling TypeScript to JavaScript...
      - npx tsc --outDir dist
      - echo Cleaning unnecessary files from node_modules...
      - modclean --run
      - echo Pruning development dependencies...
      - npm prune --production
      - cp -R node_modules dist/
      - echo Packaging the SAM application...
      - sam package --s3-bucket auto-garage-deployment --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
    - dist/**
