version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm config set maxsockets 5
      - npm config set fetch-retries 5
      - npm config set fetch-retry-mintimeout 20000
      - npm config set fetch-retry-maxtimeout 120000
      - npm cache clean --force
      - npm ci --no-audit --no-fund --prefer-offline
      - npm install -g typescript modclean
  build:
    commands:
      - echo Compiling TypeScript to JavaScript...
      - npx tsc --outDir dist
      - echo Cleaning unnecessary files from node_modules...
      - modclean --run
      - echo Pruning development dependencies...
      - npm prune --production
      - cp -R node_modules dist/
      - echo Packaging the SAM application...
      - sam package --s3-bucket auto-garage-deployment --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
    - dist/**
