version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - ulimit -n 65536  # Increase the file descriptor limit
      - npm install -g npm@latest  # Update npm to the latest version
      - npm cache clean --force  # Clear npm cache
      - npm ci --no-audit --no-fund  # Install dependencies with reduced output
      - npm install -g typescript modclean
  build:
    commands:
      - echo Compiling TypeScript to JavaScript...
      - npx tsc --outDir dist
      - echo Cleaning unnecessary files from node_modules...
      - modclean --run
      - echo Pruning development dependencies...
      - npm prune --production
      - cp -R node_modules dist/
      - echo Packaging the SAM application...
      - sam package --s3-bucket auto-garage-deployment --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
    - dist/**
