AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  AutoGarage Backend - Serverless Application

Resources:
  # Lambda Function: Get Services
  GetServicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/get.handler
      Runtime: nodejs16.x
      CodeUri: dist/
      Description: Get a list of services
      MemorySize: 128
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /services
            Method: GET

  # Lambda Function: Create Service
  CreateServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/create.handler
      Runtime: nodejs16.x
      CodeUri: dist/
      Description: Create a new service
      MemorySize: 128
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        PostApi:
          Type: Api
          Properties:
            Path: /services
            Method: POST

  # DynamoDB Table for Services
  ServicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Services
      AttributeDefinitions:
        - AttributeName: ServiceID
          AttributeType: S
      KeySchema:
        - AttributeName: ServiceID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
