AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: AutoGarage Backend - Serverless Application

Resources:
  # Incluir API Gateway
  <<: *api
  <<: *lambdas
  <<: *dynamodb


Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: The environment this stack is deployed to.
  
  JwtSecret:
    Type: String
    Description: The secret key for signing JWT tokens.


