AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: AutoGarage Backend - Serverless Application

Resources:
  # Incluir API Gateway
  !Include infraestructura/api.yaml

  # Incluir Lambdas
  !Include infraestructura/lambdas.yaml

  # Incluir DynamoDB
  !Include infraestructura/dynamodb.yaml
