AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Nested Stack for AutoGarage

Resources:
# Definición del API Gateway
  AutoGarageApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: auto-garage-api
      StageName: Dev
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
  LambdasStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: infraestructura/lambdas.yaml
  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: infraestructura/dynamodb.yaml


Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: The environment this stack is deployed to.
  
  JwtSecret:
    Type: String
    Description: The secret key for signing JWT tokens.


