# Tabla Services
  ServicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Services
      AttributeDefinitions:
        - AttributeName: ServiceID
          AttributeType: S
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: ServiceID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: NameIndex
          KeySchema:
            - AttributeName: Name
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  # Tabla Vehicles
  VehiclesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Vehicles
      AttributeDefinitions:
        - AttributeName: VehicleID
          AttributeType: S
        - AttributeName: OwnerID
          AttributeType: S
      KeySchema:
        - AttributeName: VehicleID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: OwnerIndex
          KeySchema:
            - AttributeName: OwnerID
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  # Tabla Clients
  ClientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Clients
      AttributeDefinitions:
        - AttributeName: ClientID
          AttributeType: S
        - AttributeName: Email
          AttributeType: S
      KeySchema:
        - AttributeName: ClientID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: Email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  # Tabla WorkOrders
  WorkOrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WorkOrders
      AttributeDefinitions:
        - AttributeName: WorkOrderID
          AttributeType: S
        - AttributeName: ClientID
          AttributeType: S
        - AttributeName: VehicleID
          AttributeType: S
      KeySchema:
        - AttributeName: WorkOrderID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ClientIndex
          KeySchema:
            - AttributeName: ClientID
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: VehicleIndex
          KeySchema:
            - AttributeName: VehicleID
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  # Tabla Invoices
  InvoicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Invoices
      AttributeDefinitions:
        - AttributeName: InvoiceID
          AttributeType: S
        - AttributeName: ClientID
          AttributeType: S
      KeySchema:
        - AttributeName: InvoiceID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ClientIndex
          KeySchema:
            - AttributeName: ClientID
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  # Tabla Users
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: UserID
          AttributeType: S
        - AttributeName: Email
          AttributeType: S
      KeySchema:
        - AttributeName: UserID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: Email
              KeyType: HASH
            Projection:
              ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

