# Lambda Function: Get Services
  GetServicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/get.handler
      Runtime: nodejs20.x
      CodeUri: dist/
      Description: Get a list of services
      MemorySize: 128
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole
        - PolicyName: DynamoDBScanPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                Resource: arn:aws:dynamodb:us-east-1:637423663433:table/Services
      Events:
        GetApi:
          Type: Api
          Properties:
            RestApiId: !Ref AutoGarageApi
            Path: /services
            Method: GET

  # Lambda Function: Create Service
  CreateServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/create.handler
      Runtime: nodejs20.x
      CodeUri: dist/
      Description: Create a new service
      MemorySize: 128
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref AutoGarageApi
            Path: /services
            Method: POST